# This is a basic workflow to help you get started with Actions

name: Greetings

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name:
        description: 'Your Name'
        default: 'there!'
        required: true
      message:
        description: 'Your additional message'
        default: 'This is a default message.'
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet Name
        run: echo "Hello ${{ github.event.inputs.name }}"
      - name: Ouput Message
        run: echo "Message:" "${{ github.event.inputs.message }}"
  # This workflow contains a single job called "build"
  ##build:
    # The type of runner that the job will run on
    ##runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    ##steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      ##- uses: actions/checkout@v4

      # Runs a single command using the runners shell
      ##- name: Run a one-line script
        ##run: echo Hello, world!

      # Runs a set of commands using the runners shell
      ##- name: Run a multi-line script
        ##run: |
          ##echo Add other actions to build,
          ##echo test, and deploy your project.
